# Generated by Django 4.0.5 on 2022-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessstat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fitnessstat',
            name='metric',
            field=models.CharField(choices=[('steps', 'steps'), ('calories', 'calories'), ('distance', 'distance')], max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='fitnessstat',
            unique_together={('tracked_on', 'metric', 'team_member')},
        ),
    ]
