# Generated by Django 4.0.5 on 2022-06-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fitnessstat_file_alter_fitnessstat_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessstat',
            name='value',
            field=models.FloatField(),
        ),
    ]
